'use client'

import { useState, useEffect } from 'react'

interface KitItem {
  kit_id: string
    product_id: string
      quantity: number
      }

      interface ProductData {
        id: string
          name: string
            quantity: number
            }

            export default function Home() {
              const [kits, setKits] = useState<KitItem[]>([])
                const [products, setProducts] = useState<ProductData[]>([])
                  const [loading, setLoading] = useState(true)

                    useEffect(() => {
                        const fetchData = async () => {
                              try {
                                      setLoading(true)
                                              // Placeholder: In a real app, this would fetch from your Supabase database
                                                      const mockKits: KitItem[] = [
                                                                { kit_id: 'kit1', product_id: 'prod1', quantity: 5 },
                                                                          { kit_id: 'kit1', product_id: 'prod2', quantity: 3 },
                                                                                  ]
                                                                                          const mockProducts: ProductData[] = [
                                                                                                    { id: 'prod1', name: 'Product 1', quantity: 100 },
                                                                                                              { id: 'prod2', name: 'Product 2', quantity: 200 },
                                                                                                                      ]
                                                                                                                              setKits(mockKits)
                                                                                                                                      setProducts(mockProducts)
                                                                                                                                            } catch (error) {
                                                                                                                                                    console.error('Error fetching data:', error)
                                                                                                                                                          } finally {
                                                                                                                                                                  setLoading(false)
                                                                                                                                                                        }
                                                                                                                                                                            }
                                                                                                                                                                            
                                                                                                                                                                                fetchData()
                                                                                                                                                                                  }, [])
                                                                                                                                                                                  
                                                                                                                                                                                    if (loading) {
                                                                                                                                                                                        return (
                                                                                                                                                                                              <main className="min-h-screen bg-gray-100 p-8">
                                                                                                                                                                                                      <div className="max-w-4xl mx-auto">
                                                                                                                                                                                                                <h1 className="text-4xl font-bold mb-8">Kit Warehouse Manager</h1>
                                                                                                                                                                                                                          <p>Loading...</p>
                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                        </main>
                                                                                                                                                                                                                                            )
                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                return (
                                                                                                                                                                                                                                                    <main className="min-h-screen bg-gray-100 p-8">
                                                                                                                                                                                                                                                          <div className="max-w-4xl mx-auto">
                                                                                                                                                                                                                                                                  <h1 className="text-4xl font-bold mb-8 text-gray-900">Kit Warehouse Manager</h1>
                                                                                                                                                                                                                                                                          
                                                                                                                                                                                                                                                                                  <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                                                                                                                                                                                                                                                                                            {/* Products Section */}
                                                                                                                                                                                                                                                                                                      <div className="bg-white rounded-lg shadow-md p-6">
                                                                                                                                                                                                                                                                                                                  <h2 className="text-2xl font-semibold mb-4 text-gray-800">Products</h2>
                                                                                                                                                                                                                                                                                                                              <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                            {products.map((product) => (
                                                                                                                                                                                                                                                                                                                                                            <div key={product.id} className="p-3 border border-gray-200 rounded">
                                                                                                                                                                                                                                                                                                                                                                              <p className="font-medium text-gray-900">{product.name}</p>
                                                                                                                                                                                                                                                                                                                                                                                                <p className="text-sm text-gray-600">Stock: {product.quantity}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                              ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                              {/* Kits Section */}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <div className="bg-white rounded-lg shadow-md p-6">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    <h2 className="text-2xl font-semibold mb-4 text-gray-800">Kit Composition</h2>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="space-y-3">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {kits.map((item, idx) => (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div key={idx} className="p-3 border border-blue-200 rounded bg-blue-50">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <p className="font-medium text-gray-900">Kit: {item.kit_id}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-sm text-gray-600">Product: {item.product_id} x {item.quantity}</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="mt-12 bg-blue-50 p-6 rounded-lg border border-blue-200">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3 className="text-xl font-semibold mb-2 text-gray-900">Welcome to Warehouse Kit Manager</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-gray-700">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      This application helps you manage which products and quantities compose each kit in your warehouse.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Connect to Supabase to manage your data.
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
